# Example:
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-demo-service
  namespace: backstage-demo
  description: Backstage demo service
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: app=backstage-demo-service
    github.com/project-slug: floriandorau/backstage-demo-service
    argocd/app-name: backstage-demo-service
  tags:
    - backstage-demo
  links:
    - title: Gitub Repo
      url: https://github.com/floriandorau/backstage-demo-service
spec:
  type: service
  lifecycle: production
  owner: group:guests
  providesApis:
    - backstage-demo-user-api-v1
    - backstage-demo-user-api-v2    
  consumesApis:
    - backstage-demo-user-async-api-v1
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backstage-demo-user-api-v1
  namespace: backstage-demo
  description: Users API v1
  tags:
    - users
    - rest
spec:
  type: openapi
  lifecycle: deprecated
  owner: guests
  definition:
    $text: ./api/v1/openapi.yaml
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backstage-demo-user-async-api-v1
  namespace: backstage-demo
  description: Users Async API v1
  tags:
    - users
    - rest
spec:
  type: asyncapi
  lifecycle: production
  system: system:backstage-demo-service
  owner: guests
  definition:
    $text: ./api/v1/asyncapi.yaml
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backstage-demo-user-api-v2
  namespace: backstage-demo
  description: Users API v2
  tags:
    - users
    - rest
spec:
  type: openapi
  lifecycle: experimental
  owner: guests
  definition:
    $text: ./api/v2/openapi.yaml